language: node_js
before_script:
- npm install -g gatsby-cli
node_js:
- stable
git:
  depth: 3
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: public
  skip_cleanup: true
  on:
    branch: source
env:
  global:
    secure: N0X0xtjzWuiStwbNuZIRheXYHqcFwqYwcLP3hX6wxNqnXpnR5r9U2o3NvReA67ou9+eOU3Nvd+xMZa9FWaC8avYjDBMGismflym9ri4ya6Ls51GQj6J+ujpb3vtQQ0Ps8lAyeCHWHZUZtOnAW74fPKIobtppZZWq1NROOvklk5P/+qB7vKqb2jVgY4ozI6iEIZ7LtXKIbO/noEHxzV0zCcpV2SORuHWVkXY2j/rOZaWGBja39P9GGHbN4SGYhUHosasZKSbtxcH6MvFDqjA9lAglKvqLK7cNApP/xcmW3MQIjejaslMhcIMcgl7ilHVH+Fdq++1RI7VNkjzSTFQN7g1iyxELA3U8jsxIn7RQnItwSyx3zY/GehtCfTJ3uL+ySEq5LDvobc4/9l25ctHbCDNpKM8a2TxRdL7CLc43NN7XSw4kAiMzLXDUFjAmpEVZpZn3zIsYGQ7PwfioaMiBOOKF2D3Lz8X1uPDMS6+n3K9KAx6SISa8sN3hR6HEwZQ0eEQ3aZlNl0Yv9c006SLWh0VQqMXXPcjgj2GDV3RTHwDiPSjXs6/MoKaRJ6n1mTGj5SK0+1uZt+NJrbnagwxNG8b6YH5T7qfWcksWeQXKHgdSZ+pTTT20v2jA+YkXfk7u8zkLyQu6p78NRCW4bUg2V1WoBsCEY+XWQDriVs92fYQ=
