language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "stable"
git:
  depth: 3
cache:
  directories:
  - node_modules
script: 
  - yarn build
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: source