language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
git:
  depth: 3
script: 
  - yarn build
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: yarn install && yarn run github:deploy
  skip_cleanup: true
  on:
    branch: source